### Login with the master
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = allRoleMaster &
password = allRole


### Night 1
POST http://localhost:8080/lupus/game/actions/sheriff-carpenter-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"allRole2",
      "role":"illusionist",
      "target":"allRole12"
    },
    {
      "player":"allRole8",
      "role":"knight",
      "target":"allRole17"
    },
    {
      "player":"allRole9",
      "role":"plague spreader",
      "target":"allRole5"
    },
    {
      "player":"allRole10",
      "role":"berserker",
      "target":"allRole4"
    },
    {
      "player":"allRole10",
      "role":"berserker",
      "target":"allRole11"
    },
    {
      "player":"allRole11",
      "role":"medium",
      "target":"allRole1"
    },
    {
      "player":"allRole13",
      "role":"dorky",
      "target":"allRole9"
    },
    {
      "player":"allRole15",
      "role":"seer",
      "target":"allRole13"
    },
    {
      "player":"allRole18",
      "role":"sheriff",
      "target":"allRole23"
    }
  ]
}


### Day 1
POST http://localhost:8080/lupus/game/actions/sheriff-carpenter-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"allRole1",
      "role":"puppy",
      "target":"allRole3"
    },
    {
      "player":"allRole2",
      "role":"illusionist",
      "target":"allRole3"
    },
    {
      "player":"allRole3",
      "role":"hobbit",
      "target":"allRole5"
    },
    {
      "player":"allRole4",
      "role":"kamikaze",
      "target":"allRole6"
    },
    {
      "player":"allRole5",
      "role":"giuda",
      "target":"allRole1"
    },
    {
      "player":"allRole6",
      "role":"explorer",
      "target":"allRole1"
    },
    {
      "player":"allRole7",
      "role":"jester",
      "target":"allRole12"
    },
    {
      "player":"allRole8",
      "role":"knight",
      "target":"allRole12"
    },
    {
      "player":"allRole9",
      "role":"plague spreader",
      "target":"allRole12"
    },
    {
      "player":"allRole10",
      "role":"berserker",
      "target":"allRole5"
    },
    {
      "player":"allRole11",
      "role":"medium",
      "target":"allRole12"
    },
    {
      "player":"allRole12",
      "role":"wolf",
      "target":"allRole15"
    },
    {
      "player":"allRole13",
      "role":"dorky",
      "target":"allRole22"
    },
    {
      "player":"allRole14",
      "role":"sam",
      "target":"allRole1"
    },
    {
      "player":"allRole15",
      "role":"seer",
      "target":"allRole9"
    },
    {
      "player":"allRole16",
      "role":"carpenter",
      "target":"allRole6"
    },
    {
      "player":"allRole17",
      "role":"hamster",
      "target":"allRole8"
    },
    {
      "player":"allRole18",
      "role":"sheriff",
      "target":"allRole24"
    },
    {
      "player":"allRole19",
      "role":"farmer",
      "target":"allRole21"
    },
    {
      "player":"allRole20",
      "role":"farmer",
      "target":"allRole1"
    },
    {
      "player":"allRole21",
      "role":"farmer",
      "target":"allRole8"
    },
    {
      "player":"allRole22",
      "role":"farmer",
      "target":"allRole5"
    },
    {
      "player":"allRole23",
      "role":"farmer",
      "target":"allRole1"
    },
    {
      "player":"allRole24",
      "role":"farmer",
      "target":"allRole12"
    },
    {
      "player":"allRole1",
      "role":"puppy",
      "target":"allRole1"
    },
    {
      "player":"allRole2",
      "role":"illusionist",
      "target":"allRole1"
    },
    {
      "player":"allRole3",
      "role":"hobbit",
      "target":"allRole12"
    },
    {
      "player":"allRole5",
      "role":"giuda",
      "target":"allRole1"
    },
    {
      "player":"allRole6",
      "role":"explorer",
      "target":"allRole12"
    },
    {
      "player":"allRole7",
      "role":"jester",
      "target":"allRole12"
    },
    {
      "player":"allRole8",
      "role":"knight",
      "target":"allRole1"
    },
    {
      "player":"allRole9",
      "role":"plague spreader",
      "target":"allRole12"
    },
    {
      "player":"allRole12",
      "role":"wolf",
      "target":"allRole1"
    },
    {
      "player":"allRole13",
      "role":"dorky",
      "target":"allRole12"
    },
    {
      "player":"allRole14",
      "role":"sam",
      "target":"allRole12"
    },
    {
      "player":"allRole15",
      "role":"seer",
      "target":"allRole1"
    },
    {
      "player":"allRole16",
      "role":"carpenter",
      "target":"allRole12"
    },
    {
      "player":"allRole17",
      "role":"hamster",
      "target":"allRole12"
    },
    {
      "player":"allRole19",
      "role":"farmer",
      "target":"allRole1"
    },
    {
      "player":"allRole20",
      "role":"farmer",
      "target":"allRole12"
    },
    {
      "player":"allRole21",
      "role":"farmer",
      "target":"allRole12"
    },
    {
      "player":"allRole22",
      "role":"farmer",
      "target":"allRole12"
    },
    {
      "player":"allRole23",
      "role":"farmer",
      "target":"allRole12"
    },
    {
      "player":"allRole24",
      "role":"farmer",
      "target":"allRole1"
    }
  ]
}


### Night 2
POST http://localhost:8080/lupus/game/actions/sheriff-carpenter-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"allRole2",
      "role":"illusionist",
      "target":"allRole1"
    },
    {
      "player":"allRole6",
      "role":"explorer",
      "target":"allRole7"
    },
    {
      "player":"allRole8",
      "role":"knight",
      "target":"allRole7"
    },
    {
      "player":"allRole9",
      "role":"plague spreader",
      "target":"allRole5"
    },
    {
      "player":"allRole13",
      "role":"dorky",
      "target":"allRole3"
    },
    {
      "player":"allRole15",
      "role":"seer",
      "target":"allRole23"
    }
  ]
}