### do the Login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = newGameM &
password = newGame

### PLAYER NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "userX"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### NOT VALID JSON

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality_NOT_EXISTS": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### ROLE NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "cat",
      "cardinality" : 1
    }
  ]
}

### NUMBERS OF PLAYERS AND ROLES NOT CORRESPONDS

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 1
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### INCORRECT CARDINALITY

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 2
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### PLAYER ALREADY IN GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "allRole1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### CORRECT GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "newGame1"
    },
    {
      "username": "newGame2"
    },
    {
      "username": "newGame3"
    },
    {
      "username": "newGame4"
    },
    {
      "username": "newGame5"
    },
    {
      "username": "newGame6"
    },
    {
      "username": "newGame7"
    },
    {
      "username": "newGame8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

###
GET http://localhost:8080/lupus/game/settings HTTP/1.1