### Login with the master
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123

### Test with first Action ok, and the others wrong
POST http://localhost:8080/lupus/game/actions/dorky-farmer-explorer HTTP/1.1
Content-Type: application/json

{
 "gameAction": [
   {
     "player":"user1",
     "role":"wolf",
     "target":"user1"
   },
   {
     "player":"user2",
     "role":"dorky",
     "target":"player2"
   },
   {
     "player":"user3",
     "role":"hamster",
     "target":"user3"
   }
 ]
}

### Test with first two Actions ok, the last wrong (player0 not in the same game)
POST http://localhost:8080/lupus/game/actions/dorky-farmer-explorer HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"user1",
      "role":"wolf",
      "target":"user1"
    },
    {
      "player":"user2",
      "role":"seer",
      "target":"user1"
    },
    {
      "player":"user3",
      "role":"jester",
      "target":"player0"
    }
  ]
}

### Test with all Actions ok
POST http://localhost:8080/lupus/game/actions/dorky-farmer-explorer HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"user1",
      "role":"dorky",
      "target":"user8"
    },
    {
      "player":"user8",
      "role":"sheriff",
      "target":"user4"
    },
    {
      "player":"user7",
      "role":"knight",
      "target":"user6"
    },
    {
      "player":"user9",
      "role":"wolf",
      "target":"user3"
    }
  ]
}


### login as master player0
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = player0 &
password = ciao

### Test day phase no ballot
POST http://localhost:8080/lupus/game/actions/farmer-wolf-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"player1",
      "role":"knight",
      "target":"player4"
    },
    {
      "player":"player2",
      "role":"carpenter",
      "target":"player4"
    },
    {
      "player":"player3",
      "role":"jester",
      "target":"player4"
    },
    {
      "player":"player4",
      "role":"sheriff",
      "target":"player9"
    },
    {
      "player":"player5",
      "role":"seer",
      "target":"player4"
    },
    {
      "player":"player6",
      "role":"plague spreader",
      "target":"player9"
    },
    {
      "player":"player7",
      "role":"wolf",
      "target":"player9"
    },
    {
      "player":"player8",
      "role":"wolf",
      "target":"player5"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    }
  ]
}

### Test day phase sam
POST http://localhost:8080/lupus/game/actions/farmer-wolf-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"player1",
      "role":"knight",
      "target":"player4"
    },
    {
      "player":"player2",
      "role":"carpenter",
      "target":"player4"
    },
    {
      "player":"player3",
      "role":"jester",
      "target":"player4"
    },
    {
      "player":"player4",
      "role":"sheriff",
      "target":"player9"
    },
    {
      "player":"player5",
      "role":"seer",
      "target":"player9"
    },
    {
      "player":"player6",
      "role":"plague spreader",
      "target":"player9"
    },
    {
      "player":"player7",
      "role":"wolf",
      "target":"player9"
    },
    {
      "player":"player8",
      "role":"wolf",
      "target":"player9"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    }
  ]
}

### Test day phase carpenter
POST http://localhost:8080/lupus/game/actions/farmer-wolf-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"player1",
      "role":"knight",
      "target":"player2"
    },
    {
      "player":"player2",
      "role":"carpenter",
      "target":"player4"
    },
    {
      "player":"player3",
      "role":"jester",
      "target":"player2"
    },
    {
      "player":"player4",
      "role":"sheriff",
      "target":"player2"
    },
    {
      "player":"player5",
      "role":"seer",
      "target":"player2"
    },
    {
      "player":"player6",
      "role":"plague spreader",
      "target":"player2"
    },
    {
      "player":"player7",
      "role":"wolf",
      "target":"player2"
    },
    {
      "player":"player8",
      "role":"wolf",
      "target":"player2"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    }
  ]
}

### Test day phase ballot
POST http://localhost:8080/lupus/game/actions/farmer-wolf-sam HTTP/1.1
Content-Type: application/json

{
  "gameAction": [
    {
      "player":"player1",
      "role":"knight",
      "target":"player2"
    },
    {
      "player":"player2",
      "role":"carpenter",
      "target":"player4"
    },
    {
      "player":"player3",
      "role":"jester",
      "target":"player2"
    },
    {
      "player":"player4",
      "role":"sheriff",
      "target":"player2"
    },
    {
      "player":"player5",
      "role":"seer",
      "target":"player4"
    },
    {
      "player":"player6",
      "role":"plague spreader",
      "target":"player4"
    },
    {
      "player":"player7",
      "role":"wolf",
      "target":"player2"
    },
    {
      "player":"player8",
      "role":"wolf",
      "target":"player9"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    },
    {
      "player":"player1",
      "role":"knight",
      "target":"player2"
    },
    {
      "player":"player2",
      "role":"carpenter",
      "target":"player4"
    },
    {
      "player":"player3",
      "role":"jester",
      "target":"player2"
    },
    {
      "player":"player4",
      "role":"sheriff",
      "target":"player2"
    },
    {
      "player":"player5",
      "role":"seer",
      "target":"player4"
    },
    {
      "player":"player6",
      "role":"plague spreader",
      "target":"player4"
    },
    {
      "player":"player7",
      "role":"wolf",
      "target":"player2"
    },
    {
      "player":"player8",
      "role":"wolf",
      "target":"player2"
    },
    {
      "player":"player9",
      "role":"sam",
      "target":"player4"
    }
  ]
}