-- CREATE DATABASE lupusdb;
--
-- CREATE TABLE IF NOT EXISTS lupusdb.users (
--     user_id SERIAL PRIMARY KEY,
--     username VARCHAR(50) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     password VARCHAR(100) NOT NULL
--     );
--
-- INSERT INTO users (username, email, password) VALUES ('esempio', 'esempio@example.com', 'password123');
-- INSERT INTO users (username, email, password) VALUES ('2esempio2', 'esempio@example.com', 'password123');