### Correct Login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123

### Correct Login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = user1 &
password = ciao

### Correct logout
POST http://localhost:8080/lupus/logout HTTP/1.1

###
GET http://localhost:8080/lupus/game/settings

###
POST http://localhost:8080/lupus/game/settings
Content-Type: application/json

###
PUT http://localhost:8080/lupus/game/settings
Content-Type: application/json

### REQUIRED populate_db_optional.aaa

###
GET http://localhost:8080/lupus/game/list

###
GET http://localhost:8080/lupus/game/actions/dorky-farmer-explorer
Content-Type: application/json

###
POST http://localhost:8080/lupus/game/actions/dorky-farmer-explorer
Content-Type: application/json

###
POST http://localhost:8080/lupus/game/notExist/dorky-farmer-explorer
Content-Type: application/json

###
POST http://localhost:8080/lupus/game/status/dorky-farmer-explorer
Content-Type: application/json

###
GET http://localhost:8080/lupus/game/status/dorky-farmer-explorer
Content-Type: application/json