### do the Login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123

### VALID GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### MASTER ALREADY IN A GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "player1"
    },
    {
      "username": "player2"
    },
    {
      "username": "player3"
    },
    {
      "username": "player4"
    },
    {
      "username": "player5"
    },
    {
      "username": "player6"
    },
    {
      "username": "player7"
    },
    {
      "username": "player8"
    },
    {
      "username": "player9"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    },
    {
      "role": "sheriff",
      "cardinality" : 1
    },
    {
      "role": "plague spreader",
      "cardinality" : 1
    },
    {
      "role": "sam",
      "cardinality" : 1
    }
  ]
}

### new login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = player0 &
password = ciao

### VALID GAME 2

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "player1"
    },
    {
      "username": "player2"
    },
    {
      "username": "player3"
    },
    {
      "username": "player4"
    },
    {
      "username": "player5"
    },
    {
      "username": "player6"
    },
    {
      "username": "player7"
    },
    {
      "username": "player8"
    },
    {
      "username": "player9"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    },
    {
      "role": "sheriff",
      "cardinality" : 1
    },
    {
      "role": "plague spreader",
      "cardinality" : 1
    },
    {
      "role": "sam",
      "cardinality" : 1
    }
  ]
}

### PLAYER NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "userX"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### NOT VALID JSON

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality_NOT_EXISTS": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### ROLE NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "cat",
      "cardinality" : 1
    }
  ]
}


### NUMBERS NOT MATCH

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 1
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

### INCORRECT CARDINALITY

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 2
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}


### PLAYER ALREADY IN GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/json

{
  "player": [
    {
      "username": "user1"
    },
    {
      "username": "user2"
    },
    {
      "username": "user3"
    },
    {
      "username": "user4"
    },
    {
      "username": "user5"
    },
    {
      "username": "user6"
    },
    {
      "username": "user7"
    },
    {
      "username": "user8"
    }
  ],
  "roleCardinality": [
    {
      "role": "wolf",
      "cardinality" : 2
    },
    {
      "role": "farmer",
      "cardinality" : 2
    },
    {
      "role": "seer",
      "cardinality" : 1
    },
    {
      "role": "knight",
      "cardinality" : 1
    },
    {
      "role": "jester",
      "cardinality" : 1
    },
    {
      "role": "hamster",
      "cardinality" : 1
    }
  ]
}

