### do the Login
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123


### PLAYER NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
player9 = user42 &
wolf = 2 &
farmer = 2 &
seer = 1 &
knight = 1 &
jester = 1 &
hamster = 1

### NOT VALID PARAMETER

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player9 = user8 &
wolf = 2 &
farmer = 2 &
seer = 1 &
knight = 1 &
jester = 1

### ROLE NOT EXIST

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
wolf = 2 &
farmer = 2 &
seer = 1 &
knight = 1 &
jester = 1 &
cat = 1


### NUMBERS NOT MATCH

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
wolf = 1 &
farmer = 3 &
seer = 1 &
knight = 1 &
jester = 1


### INCORRECT CARDINALITY

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
wolf = 2 &
farmer = 2 &
seer = 2 &
knight = 1 &
jester = 1

### VALID GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
wolf = 2 &
farmer = 2 &
seer = 1 &
knight = 1 &
jester = 1 &
hamster = 1


### PLAYER ALREADY IN GAME

POST http://localhost:8080/lupus/game/settings HTTP/1.1
Content-Type: application/x-www-form-urlencoded

player1 = user1 &
player2 = user2 &
player3 = user3 &
player4 = user4 &
player5 = user5 &
player6 = user6 &
player7 = user7 &
player8 = user8 &
wolf = 2 &
farmer = 2 &
seer = 1 &
knight = 1 &
jester = 1 &
hamster = 1

