### Empty fields
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio &
email = 1@a.c &
password = password123

### not valid username
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = _esempio &
email = 1@a.it &
password = password123 &
password_rp = password123

### not valid email
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio &
email = 111 &
password = password123 &
password_rp = password123

### Passwords not complex enough
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio &
email = 1@a.it &
password = password123 &
password_rp = password123

### different passwords
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio &
email = 1@a.it &
password = abC12#A1 &
password_rp = abC12#A12

### Username already exists
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio &
email = 1@a.it &
password = abC12#A1 &
password_rp = abC12#A1

### Email already used
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = esempio23 &
email = esempio@example.com &
password = abC12#A1 &
password_rp = abC12#A1

### correct Signup
POST http://localhost:8080/lupus/player/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username = newUser12345 &
email = newUser12345@example.com &
password = abC12#A1 &
password_rp = abC12#A1