###
GET http://localhost:8080/lupus/logout HTTP/1.1

###Test for the UserMeDeleteRR added in the UserDispatcherServlet
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123

###
DELETE http://localhost:8080/lupus/user/me HTTP/1.1
Content-Type: application/json

{
  "userUpdate": {
    "oldPassword": "password12"
  }
}



###Test for the UserMePutRR added in the UserDispatcherServlet with the email
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = user1 &
password = ciao1

###
PUT http://localhost:8080/lupus/user/me HTTP/1.1
Content-Type: application/json

{
  "userUpdate": {
    "oldEmail": "user1@test.com",
    "newEmail": "user1test@test.com"
  }
}



###Test for the UserMePutRR added in the UserDispatcherServlet with the password
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = user1 &
password = ciao

###
PUT http://localhost:8080/lupus/user/me HTTP/1.1
Content-Type: application/json

{
  "userUpdate": {
    "oldPassword": "ciao",
    "newPassword": "ciao1",
    "repeatNewPassword": "ciao1"
  }
}


###
GET http://localhost:8080/lupus/user/me/friend HTTP/1.1
Content-Type: application/json



###
POST http://localhost:8080/lupus/user/me/friend HTTP/1.1
Content-Type: application/json



###Test for the DeleteFriendRR added in the UserDispatcherServlet
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = user1 &
password = ciao

###
DELETE http://localhost:8080/lupus/user/me/friend HTTP/1.1
Content-Type: application/json



###
GET http://localhost:8080/lupus/user/username/logs HTTP/1.1
Content-Type: application/json



###
GET http://localhost:8080/lupus/user/username/statistic HTTP/1.1
Content-Type: application/json



###Test for the UserUsernameGetRR added in the UserDispatcherServlet
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = user1 &
password = ciao1

###
GET http://localhost:8080/lupus/user/user5 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/lupus/user/me HTTP/1.1
Content-Type: application/json