GET http://localhost:8080/lupus/user/esempio HTTP/1.1
//Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/lupus/user/esempio111 HTTP/1.1

###
#DELETE http://localhost:8080/lupus/user/me HTTP/1.1
#Content-Type: application/x-www-form-urlencoded
#
#username = esempio

###
#PUT http://localhost:8080/lupus/user/me HTTP/1.1
#Content-Type: application/x-www-form-urlencoded