POST http://localhost:8080/lupus/user/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123

### jsp/home.jsp
GET http://localhost:8080/lupus/jsp/home.jsp HTTP/1.1

### jsp/friend.jsp
GET http://localhost:8080/lupus/jsp/friend.jsp

### Delete friend
POST http://localhost:8080/lupus/friend
Content-Type: application/x-www-form-urlencoded

action = delete
friend_username = user1

### Add friend
POST http://localhost:8080/lupus/friend
Content-Type: application/x-www-form-urlencoded

action = add
friend_username = user4