###
POST http://localhost:8080/lupus/login HTTP/1.1
#no user master or user for the game with id 1 and public id dorky-farmer-explorer
Content-Type: application/x-www-form-urlencoded

user = player0 &
password = ciao
###
GET http://localhost:8080/lupus/game/logs/dorky-farmer-explorer HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/lupus/game/logs/dorky-farmer-explorer/master HTTP/1.1
Content-Type: application/json








