###
POST http://localhost:8080/lupus/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user = esempio &
password = password123
###
GET http://localhost:8080/lupus/game/logs/dorky-farmer-explorer/master HTTP/1.1
Content-Type: application/json









